import type { Metadata } from "next";
import "./globals.css";
import Hero from "./components/Hero";
import { Themeprovider } from "./components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          {
            <>
              <Themeprovider>
                <Hero />
                {children}
              </Themeprovider>
            </>
          }
        </body>
      </html>
    </ClerkProvider>
  );
}
