import type { Metadata } from "next";
import "./globals.css";
import Hero from "./components/Hero";
import { Themeprovider } from "./components/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {
          <>
            <Themeprovider>
              <Hero />
              {children}
            </Themeprovider>
          </>
        }
      </body>
    </html>
  );
}
